from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from jsonschema import Draft7Validator

from .llm import LLMSettings, call_chat_completion, extract_json_object
from .storage import read_project_text, write_json


def _empty_menu() -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "restaurant_name": None,
        "language": "unknown",
        "currency": "UNKNOWN",
        "categories": [
            {
                "id": "cat_01",
                "name": "Sample Menu",
                "description": "Demo fallback shown when OCR or LLM output is unavailable.",
                "category_price": None,
                "items": [
                    {
                        "id": "item_01_01",
                        "name": "Chicken Noodle Soup",
                        "price": 120,
                        "description": "Warm noodle soup with chicken.",
                        "options": [
                            {
                                "name": "Spice level",
                                "required": True,
                                "min_select": 1,
                                "max_select": 1,
                                "choices": [
                                    {"name": "Mild", "additional_price": 0},
                                    {"name": "Spicy", "additional_price": 0},
                                ],
                            }
                        ],
                        "is_recommended": True,
                        "availability": None,
                    },
                    {
                        "id": "item_01_02",
                        "name": "Vegetable Fried Rice",
                        "price": 100,
                        "description": "Rice stir-fried with seasonal vegetables.",
                        "options": [],
                        "is_recommended": False,
                        "availability": None,
                    },
                ],
            }
        ],
        "notes": ["This is a mock menu used for demo mode."],
    }


def mock_parse_menu(raw_text: str) -> dict[str, Any]:
    if not raw_text.strip():
        return _empty_menu()

    currency = "TWD" if re.search(r"NT\$|TWD|元", raw_text, re.IGNORECASE) else "UNKNOWN"
    categories: list[dict[str, Any]] = []
    current = {
        "id": "cat_01",
        "name": "Menu",
        "description": None,
        "category_price": None,
        "items": [],
    }
    categories.append(current)

    price_pattern = re.compile(r"(.+?)\s*(?:NT\$|\$|TWD|元)?\s*([0-9]+(?:\.[0-9]{1,2})?)\s*$", re.IGNORECASE)
    cat_index = 1
    item_counts = {cat_index: 0}

    for raw_line in raw_text.splitlines():
        line = raw_line.strip(" -*\t")
        if not line or line.lower().startswith("page "):
            continue
        match = price_pattern.match(line)
        if match:
            name = match.group(1).strip(" .:-")
            price = float(match.group(2))
            if not name:
                continue
            item_counts[cat_index] += 1
            current["items"].append(
                {
                    "id": f"item_{cat_index:02d}_{item_counts[cat_index]:02d}",
                    "name": name,
                    "price": price,
                    "description": None,
                    "options": [],
                    "is_recommended": False,
                    "availability": None,
                }
            )
        elif len(line) <= 30 and len(current["items"]) > 0:
            cat_index += 1
            item_counts[cat_index] = 0
            current = {
                "id": f"cat_{cat_index:02d}",
                "name": line,
                "description": None,
                "category_price": None,
                "items": [],
            }
            categories.append(current)

    categories = [category for category in categories if category["items"]]
    if not categories:
        return _empty_menu()

    return {
        "schema_version": "1.0",
        "restaurant_name": None,
        "language": "mixed",
        "currency": currency,
        "categories": categories,
        "notes": ["Generated by MenuTalker mock parser from OCR text. Use an external LLM for production parsing."],
    }


def validate_menu(menu: dict[str, Any]) -> list[str]:
    schema = json.loads(read_project_text("menu.schema.json"))
    validator = Draft7Validator(schema)
    errors = sorted(validator.iter_errors(menu), key=lambda error: list(error.path))
    return [f"{'/'.join(map(str, error.path)) or '<root>'}: {error.message}" for error in errors]


def parse_menu(
    raw_text: str,
    image_paths: list[Path],
    session_dir: Path,
    settings: LLMSettings,
) -> tuple[dict[str, Any], Path, list[str]]:
    warnings: list[str] = []
    if settings.provider == "mock":
        menu = mock_parse_menu(raw_text)
    else:
        prompt = read_project_text("prompts/prompt_Menu_Structure_Parsing.md")
        schema = read_project_text("menu.schema.json")
        user_prompt = (
            f"{prompt}\n\n"
            "menu.schema.json:\n"
            f"{schema}\n\n"
            "menu_raw_text.txt:\n"
            f"{raw_text}\n"
        )
        try:
            content = call_chat_completion(
                settings,
                system_prompt="You produce strict JSON for MenuTalker.",
                user_prompt=user_prompt,
                image_paths=image_paths,
            )
            menu = extract_json_object(content)
        except Exception as exc:
            warnings.append(
                "External LLM menu parsing failed; generated a fallback menu from OCR text instead. "
                f"Reason: {exc}"
            )
            menu = mock_parse_menu(raw_text)

    validation_errors = validate_menu(menu)
    warnings.extend(validation_errors)
    menu_path = write_json(session_dir / "menu.json", menu)
    return menu, menu_path, warnings
